steps:
- id: install_dependencies
  name: us-east4-docker.pkg.dev/htm-332202/shared-404-repo/node-build:latest
  entrypoint: npm
  args: ['install']
- id: build
  name: us-east4-docker.pkg.dev/htm-332202/shared-404-repo/node-build:latest
  entrypoint: npm
  args: ['run', 'build']
  waitFor: [install_dependencies]
<<<<<<< HEAD
- id: test
  name: node:17-alpine3.12
  entrypoint: npm
  args: ['test']
  waitFor: ['build']
=======
- id: install_puppeteer
  name: node:17-alpine3.12
  entrypoint: npm
  args: ['install', 'puppeteer']
>>>>>>> master
- id: deploy
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m','rsync','-r','-d', './dist/site404-js', '${_SERVER_BUCKET_PATH}']
  waitFor: ['test']
- id: invalidate_cache
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute','url-maps','invalidate-cdn-cache', '${_LOAD_BALANCER_NAME}', '--path=/*']
  waitFor: [deploy]