steps:
- id: install
  name: node:17-alpine3.12
  entrypoint: npm
  args: ['install']
- id: build
  name: node:17-alpine3.12
  entrypoint: npm
  args: ['run', 'build']
  waitFor:
  - install
- id: deploy
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m','rsync','-r','-d', './dist/site404-js', '${_SERVER_BUCKET_PATH}']
  waitFor:
  - build
- id: invalidate_cache
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute','url-maps','invalidate-cdn-cache', '${_LOAD_BALANCER_NAME}', '--path=/*']
  waitFor: 
  - deploy