steps:
- id: install_dependencies
  name: node:17-alpine3.12
  entrypoint: npm
  args: ['install']
- id: build
  name: node:17-alpine3.12
  entrypoint: npm
  args: ['run', 'build']
  waitFor:
  - install_dependencies
- id: test
  name: node:17-alpine3.12
  entrypoint: bash
  args:
    - '-c' 
    - |
    apk add firefox 
    npm test
  env: ['FIREFOX_BIN=/usr/bin/firefox']
  waitFor: ['build']
- id: deploy
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m','rsync','-r','-d', './dist/site404-js', '${_SERVER_BUCKET_PATH}']
  waitFor: ['build']
- id: invalidate_cache
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute','url-maps','invalidate-cdn-cache', '${_LOAD_BALANCER_NAME}', '--path=/*']
  waitFor: [deploy]