steps:
- id: install
  name: node
  entrypoint: npm
  args: ['install']
- id: build
  name: 'node'
  args:
  - 'run'
  - 'build'
  waitFor:
  - install
- id: copy_files
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','-r','-m', 'dist/site404-js/*', '\${_SERVER_BUCKET_PATH}']
  waitFor:
  - build
- id: set_website_configuration
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['web', 'set', '-m', 'index.html','\${_SERVER_BUCKET_PATH}']
  waitFor:
  - copy_files

