steps:
- id: install_dependencies
  name: node:17-alpine3.12
  entrypoint: npm
  args: ['install']
- id: build
  name: node:17-alpine3.12
  entrypoint: npm
  args: ['run', 'build']
  waitFor:
  - install_dependencies
- id: install_firefox
  name: node:17-alpine3.12
  entrypoint: apk
  args: ['add', 'firefox']
- id: test
  name: node:17-alpine3.12
  entrypoint: npm
  args: ['test']
  waitFor: ['build', 'install_firefox']
- id: deploy
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m','rsync','-r','-d', './dist/site404-js', '${_SERVER_BUCKET_PATH}']
  waitFor: ['build']
- id: invalidate_cache
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute','url-maps','invalidate-cdn-cache', '${_LOAD_BALANCER_NAME}', '--path=/*']
  waitFor: [deploy]